apps/search/urls.py
# Amara, universalsubtitles.org
# 
# Copyright (C) 2013 Participatory Culture Foundation
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see 
# http://www.gnu.org/licenses/agpl-3.0.html.

from django.conf.urls import url

from search import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^router/$', views.rpc_router, name='rpc_router'),
    url(r'^router/api/$', views.rpc_router.api, name='rpc_api'),
]

apps/teams/urls.py
# Amara, universalsubtitles.org
#
# Copyright (C) 2013 Participatory Culture Foundation
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see
# http://www.gnu.org/licenses/agpl-3.0.html.

from django.views.generic.base import TemplateView
from django.conf.urls import url
from teams.rpc import rpc_router

from teams import views, new_views
import externalsites.views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^my/$', views.index, {'my_teams': True}, name='user_teams'),
    url(r'^create/$', views.create, name='create'),
    url(r'^router/$', rpc_router, name='rpc_router'),
    url(r'^router/api/$', rpc_router.api, name='rpc_api'),
    url(r'^tasks/perform/$', views.perform_task, name='perform_task'),
    url(r'^invite/accept/(?P<invite_pk>\d+)/$', views.accept_invite, name='accept_invite'),
    url(r'^invite/deny/(?P<invite_pk>\d+)/$', views.accept_invite, {'accept': False}, name='deny_invite'),
    url(r'^leave_team/(?P<slug>[-\w]+)/$', views.leave_team, name='leave'),
    url(r'^highlight/(?P<slug>[-\w]+)/$', views.highlight, name='highlight'),
    url(r'^unhighlight/(?P<slug>[-\w]+)/$', views.highlight, {'highlight': False}, name='unhighlight'),
    url(r'^(?P<slug>[-\w]+)/approvals/$', views.approvals, name='approvals'),
    url(r'^(?P<slug>[-\w]+)/application/approve/(?P<application_pk>\d+)/$',
        views.approve_application, name='approve_application'),
    url(r'^(?P<slug>[-\w]+)/application/deny/(?P<application_pk>\d+)/$',
        views.deny_application, name='deny_application'),
    url(r'^move/$', views.move_video, name='move_video'),
    url(r'^(?P<slug>[-\w]+)/move-videos/$', views.move_videos, name='move_videos'),
    url(r'^add/video/(?P<slug>[-\w]+)/$', views.add_video, name='add_video'),
    url(r'^add/videos/(?P<slug>[-\w]+)/$', views.add_videos, name='add_videos'),
    url(r'^add-video-to-team/(?P<video_id>(\w|-)+)/', views.add_video_to_team, name='add_video_to_team'),
    url(r'^edit/video/(?P<team_video_pk>\d+)/$', views.team_video, name='team_video'),
    url(r'^remove/video/(?P<team_video_pk>\d+)/$', views.remove_video, name='remove_video'),
    url(r'^remove/members/(?P<slug>[-\w]+)/(?P<user_pk>\d+)/$', views.remove_member, name='remove_member'),
    url(r'^(?P<slug>[-\w]+)/members/role-saved/$', views.role_saved, name='role_saved'),
    url(r'^(?P<slug>[-\w]+)/members/search/$', views.search_members, name='search_members'),
    url(r'^(?P<slug>[-\w]+)/members/(?P<role>(admin|manager|contributor))/$',
        views.detail_members, name='detail_members_role'),
    url(r'^(?P<slug>[-\w]+)/projects/$', views.project_list, name='project_list'),
    url(r'^(?P<slug>[-\w]+)/tasks/$', views.team_tasks, name='team_tasks'),
    url(r'^(?P<slug>[-\w]+)/create-task/(?P<team_video_pk>\d+)/$', views.create_task, name='create_task'),
    url(r'^(?P<slug>[-\w]+)/delete-task/$', views.delete_task, name='delete_task'),
    url(r'^(?P<slug>[-\w]+)/upload-draft/(?P<video_id>\w+)/$', views.upload_draft, name='upload_draft'),
    url(r'^(?P<slug>[-\w]+)/(?P<task_pk>\d+)/download/(?P<type>[-\w]+)/$',
        views.download_draft, name='download_draft'),
    url(r'^(?P<slug>[-\w]+)/assign-task/$', views.assign_task, name='assign_task'),
    url(r'^(?P<slug>[-\w]+)/assign-task/a/$', views.assign_task_ajax, name='assign_task_ajax'),
    url(r'^(?P<slug>[-\w]+)/tasks/(?P<task_pk>\d+)/perform/$', views.perform_task, name='perform_task'),
    url(r'^(?P<slug>[-\w]+)/tasks/(?P<task_pk>\d+)/perform/$', views.perform_task, name='perform_task'),
    url(r'^(?P<slug>[-\w]+)/feeds/(?P<feed_id>\d+)$', views.video_feed, name='video_feed'),
    url(r'^(?P<slug>[-\w]+)/settings/projects/add/$', views.add_project, name='add_project'),
    url(r'^(?P<slug>[-\w]+)/settings/languages/$', views.settings_languages, name='settings_languages'),
    # just /p/ will bring all videos on any projects
    url(r'^(?P<slug>[-\w]+)/p/(?P<project_slug>[-\w]+)?/?$', views.detail, name='project_video_list'),
    # TODO: Review these...
    url(r'^(?P<slug>[-\w]+)/p/(?P<project_slug>[-\w]+)/tasks/?$', views.team_tasks, name='project_tasks'),
    url(r'^(?P<slug>[-\w]+)/delete-language/(?P<lang_id>[\w\-]+)/', views.delete_language, name='delete-language'),
    url(r'^(?P<slug>[-\w]+)/auto-captions-status/$', views.auto_captions_status, name='auto-captions-status'),
]

urlpatterns += [
    url(r'^email_invite/(?P<signed_pk>[0-9]+/[A-Za-z0-9_=-]+)/$', new_views.email_invite, name='email_invite'),
    url(r'^email_invite/invalid/', new_views.email_invite_invalid, name='email_invite_invalid'),
    url(r'^(?P<slug>[-\w]+)/applications/$', new_views.applications, name='applications'),
    url(r'^(?P<slug>[-\w]+)/$', new_views.dashboard, name='dashboard'),
    url(r'^(?P<slug>[-\w]+)/join/$', new_views.join, name='join'),
    url(r'^(?P<slug>[-\w]+)/videos/$', new_views.videos, name='videos'),
    url(r'^(?P<slug>[-\w]+)/videos/ajax-search/$', new_views.ajax_video_search,
        name='ajax-video-search'),
    url(r'^(?P<slug>[-\w]+)/members/$', new_views.members, name='members'),
    url(r'^(?P<slug>[-\w]+)/members/(?P<username>.+)/$', new_views.member_profile, name='member-profile'),
    url(r'^(?P<slug>[-\w]+)/members/ajax-search/$', new_views.ajax_member_search,
        name='ajax-member-search'),
    url(r'^(?P<slug>[-\w]+)/inviteable_users/ajax-search/$',
        new_views.ajax_inviteable_users_search,
        name='ajax-inviteable-users-search'),
    url(r'^(?P<slug>[-\w]+)/inviteable_users/ajax-search/multiple/$',
        new_views.ajax_inviteable_users_multiple_search,
        name='ajax-inviteable-users-multiple-search'),
    url(r'^(?P<slug>[-\w]+)/members/invite/$', new_views.invite, name='invite'),
    url(r'^(?P<slug>[-\w]+)/members/add/$', new_views.add_members, name='add-members'),
    url(r'^(?P<slug>[-\w]+)/members/invite/autocomplete-user/$',
        new_views.autocomplete_invite_user, name='autocomplete-invite-user'),
    url(r'^(?P<slug>[-\w]+)/admins/$', new_views.admin_list, name='admin-list'),
    url(r'^(?P<slug>[-\w]+)/activity/$', new_views.activity, name='activity'),
    url(r'^(?P<slug>[-\w]+)/activity/videosstatistics/$', new_views.statistics,
        {'tab': 'videosstats'}, name='videosstatistics-activity'),
    url(r'^(?P<slug>[-\w]+)/activity/teamstatistics/$', new_views.statistics,
        {'tab': 'teamstats', }, name='teamstatistics-activity'),
    url(r'^(?P<slug>[-\w]+)/projects/(?P<project_slug>[-\w]+)/$', new_views.project, name='project'),
    url(r'^(?P<slug>[-\w]+)/projects/(?P<project_slug>[-\w]+)/autocomplete-manager$',
        new_views.autocomplete_project_manager, name='autocomplete-project-manager'),
    url(r'^(?P<slug>[-\w]+)/languages/$', new_views.all_languages_page, name='all-languages-page'),
    url(r'^(?P<slug>[-\w]+)/languages/(?P<language_code>[-\w]+)/$', new_views.language_page, name='language-page'),
    url(r'^(?P<slug>[-\w]+)/languages/(?P<language_code>[-\w]+)/autocomplete-manager$',
        new_views.autocomplete_language_manager, name='autocomplete-language-manager'),
    url(r'^(?P<slug>[-\w]+)/manage/videos/$', new_views.manage_videos,
        name='manage_videos'),
    url(r'^(?P<slug>[-\w]+)/manage/videos/project/(?P<project_id>[\d]+)/$',
        new_views.manage_videos, name='manage_videos_project'),
    url(r'^(?P<slug>[-\w]+)/resources/$', new_views.resources, name='resources'),
    url(r'^(?P<slug>[-\w]+)/settings/$', new_views.settings_basic, name='settings_basic'),
    url(r'^(?P<slug>[-\w]+)/settings/messages/$', new_views.settings_messages, name='settings_messages'),
    url(r'^(?P<slug>[-\w]+)/settings/lang-messages/$', new_views.settings_lang_messages, name='settings_lang_messages'),
    url(r'^(?P<slug>[-\w]+)/settings/feeds/$', new_views.settings_feeds, name='settings_feeds'),
    url(r'^(?P<slug>[-\w]+)/settings/projects/$', new_views.settings_projects, name='settings_projects'),
    url(r'^(?P<slug>[-\w]+)/settings/projects/(?P<project_slug>[-\w]+)/edit/$',
        new_views.edit_project, name='edit_project'),
    url(r'^(?P<slug>[-\w]+)/settings/workflows/$', new_views.settings_workflows, name='settings_workflows'),
    url(r'^(?P<slug>[-\w]+)/video-durations/$', new_views.video_durations,
        name='video-durations'),
    url(r'^(?P<slug>[-\w]+)/debug-stats/$', new_views.debug_stats, name='debug-stats'),
    url(r'^(?P<slug>[-\w]+)/resources/$', new_views.resources, name='resources'),
    url(r'^(?P<slug>[-\w]+)/settings/$', new_views.settings_basic, name='settings_basic'),
    url(r'^(?P<slug>[-\w]+)/settings/messages/$', new_views.settings_messages, name='settings_messages'),
    url(r'^(?P<slug>[-\w]+)/settings/lang-messages/$', new_views.settings_lang_messages, name='settings_lang_messages'),
    url(r'^(?P<slug>[-\w]+)/settings/permissions/$', new_views.settings_permissions, name='settings_permissions'),
    url(r'^(?P<slug>[-\w]+)/settings/feeds/$', new_views.settings_feeds, name='settings_feeds'),
    url(r'^(?P<slug>[-\w]+)/settings/projects/$', new_views.settings_projects, name='settings_projects'),
    url(r'^(?P<slug>[-\w]+)/settings/projects/(?P<project_slug>[-\w]+)/edit/$',
        new_views.edit_project, name='edit_project'),
    url(r'^(?P<slug>[-\w]+)/settings/workflows/$', new_views.settings_workflows, name='settings_workflows'),
    url(r'^(?P<slug>[-\w]+)/video-durations/$', new_views.video_durations,
        name='video-durations'),
]

urls.py
# Amara, universalsubtitles.org
#
# Copyright (C) 2013 Participatory Culture Foundation
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see
# http://www.gnu.org/licenses/agpl-3.0.html.

import importlib

from django import http
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.models import AnonymousUser
from django.shortcuts import render
from django.template import RequestContext, loader
from django.views.generic.base import TemplateView, RedirectView
from django.views.decorators.clickjacking import xframe_options_exempt
import django.contrib.auth.views
import django.views.static

from auth.forms import CustomPasswordResetForm
from utils.genericviews import JSTemplateView
import optionalapps
import api.views
import auth.views
import crossdomain_views
import teams.views
import videos.views
import views
import widget.views

admin.autodiscover()
admin.site.login = auth.views.login

def calc_homepage_view():
    module_name, func_name = settings.HOMEPAGE_VIEW.rsplit('.', 1)
    mod = importlib.import_module(module_name)
    return getattr(mod, func_name)

urlpatterns = [
    url('^500/$', TemplateView.as_view(template_name='500.html')),
    url('^404/$', TemplateView.as_view(template_name='404.html')),
    url('^robots.txt$', TemplateView.as_view(template_name='robots.txt')),
    url(r'^crossdomain.xml$',
        crossdomain_views.root_crossdomain),
    url(r'^comments/',
        include('comments.urls', namespace='comments')),
    url(r'^messages/',
        include('messages.urls', namespace='messages')),
    # TODO: Not sure what this is.  It's breaking the app under Django 1.4
    # url(r'^pcf-targetter/',
    #     include('targetter.urls', namespace='targetter')),
    url(r'^logout/', auth.views.logout, name='logout'),
    url(r'^errortest', views.errortest, name='errortest'),
    url(r'^one_time_url/(?P<token>.+)$', views.one_time_url, name='one_time_url'),
    url(r'^admin/billing/$', teams.views.billing, name='billing'),
    url(r'^admin/password_reset/$', auth.views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$',
        django.contrib.auth.views.password_reset_done,
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        '(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth.views.password_reset_confirm, {'post_reset_redirect': '/reset/done/'}, name='password_reset_confirm'),
    url(r'^reset-external/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        django.contrib.auth.views.password_reset_confirm,
        {'extra_context': {'external_account': True}, 'post_reset_redirect': '/reset/done/'},
        name='password_reset_confirm_external'),
    url(r'^reset/done/$', auth.views.password_reset_complete,
        name='password_reset_complete'),
    url(r'^styleguide/', include('styleguide.urls', namespace='styleguide')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^staff/', include('staff.urls', namespace='staff')),
    url(r'^subtitles/',
        include('subtitles.urls', namespace='subtitles')),
    url(r'^embed(?P<version_no>\d+)?.js$', widget.views.embed,
        name="widget-embed"),
    url(r'^onsite_widget/$',
        widget.views.onsite_widget, name='onsite_widget'),
    url(r'^onsite_widget_resume/$', widget.views.onsite_widget_resume,
        name='onsite_widget_resume'),
    url(r'^widget/', include('widget.urls', namespace='widget',
        app_name='widget')),
    url(r'^search/',
        include('search.urls', 'search')),
    url(r'^community$',
        TemplateView.as_view(template_name='community.html'),
        name='community'),
    url(r'^dfxp-wrapper-test/$',
        TemplateView.as_view(template_name='dfxp-wrapper-test.html'),
        name='dfxp-wrapper-test'),
    url(r'^embedder/$', TemplateView.as_view(template_name='embedder.html'),
        'embedder_page'),
    url(r'^embedder-iframe/$',
        JSTemplateView.as_view(template_name='embedder-iframe.js'),
        name='embedder_iframe'),
    url(r'^embedder-offsite/$',
        TemplateView.as_view(template_name='embedder-offsite.html'),
        name='embedder_page_offsite'),
    url(r'^embedder-widget-iframe/(?P<analytics>.*)', widget.views.embedder_widget, name='embedder_widget'),
    url(r'^streaming-transcript/$',
        TemplateView.as_view(template_name='streaming-transcript.html'),
        name='streaming_transcript_demo'),
    url(r'^w3c/p3p.xml$',
        TemplateView.as_view(template_name='p3p.xml')),
    url(r'^w3c/Policies.xml$',
        TemplateView.as_view(template_name='Policies.xml'),
        name='policy_page'),
    url(r'^about$', TemplateView.as_view(template_name='about.html'),
        name='about_page'),
    url(r'^security', TemplateView.as_view(template_name='security.html'),
        name='security_page'),
    url(r'^get-code/$',
        TemplateView.as_view(template_name='embed_page.html'),
        name='get_code_page'),
    url(r'^dmca$',  TemplateView.as_view(template_name='dmca.html'),
        name='dmca_page'),
    url(r'^faq$',  TemplateView.as_view(template_name='faq.html'),
        name='faq_page'),
    url(r'^terms$', RedirectView.as_view(url='https://about.amara.org/tos/')),
    url(r'^opensubtitles2010$',
        TemplateView.as_view(template_name='opensubtitles2010.html'),
        name='opensubtitles2010_page'),
    url(r'^test-ogg$',
        TemplateView.as_view(template_name='alpha-test01-ogg.htm'),
        name='test-ogg-page'),
    url(r'^test-mp4$',
        TemplateView.as_view(template_name='alpha-test01-mp4.htm'),
        name='test-mp4-page'),
    url(r"helpers/",
        include('testhelpers.urls', namespace='helpers')),
    url(r'^videos/', include('videos.urls', namespace='videos',
        app_name='videos')),
    url(r'^teams/', include('teams.urls', namespace='teams',
        app_name='teams')),
    url(r'^ui/', include('ui.urls', namespace='ui', app_name='ui')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles',
        app_name='profiles')),
    url(r'^externalsites/', include('externalsites.urls',
                                    namespace='externalsites',
                                    app_name='externalsites')),
    url(r'^media/', include('staticmedia.urls',
                            namespace='staticmedia',
                            app_name='staticmedia')),
    url(r'^auth/', include('auth.urls', namespace='auth', app_name='auth')),
    url(r'^auth/', include('thirdpartyaccounts.urls', namespace='thirdpartyaccounts', app_name='thirdpartyaccounts')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^api2/partners/', include('api.urls', namespace='api-legacy')),
    ## Video shortlinks
    url(r'^v/(?P<encoded_pk>\w+)/$', videos.views.shortlink,
        name='shortlink'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^commit$', RedirectView.as_view(
        url='https://github.com/pculture/unisubs/commit/{}'.format(settings.LAST_COMMIT_GUID))),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^$', calc_homepage_view(), name="home"),
]

urlpatterns.extend(optionalapps.get_urlpatterns())

urlpatterns.extend([
    url(r'^api/', api.views.index.not_found, name='api-not-found'),
])

if settings.DEBUG:
    urlpatterns += [
        url(r'^site_media/(?P<path>.*)$', django.views.static.serve,
            {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
        url(r'^user-data/(?P<path>.*)$', django.views.static.serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    ]
try:
    import debug_toolbar
except ImportError:
    pass
else:
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

def ensure_user(request):
    if not hasattr(request, 'user'):
        request.user = AnonymousUser()

def handler500(request):
    ensure_user(request)
    return render(request, '500.html', status=500)

def handler403(request, exception):
    ensure_user(request)
    return render(request, '403.html', status=403)

templates/teams/_search_js.html
<script type="text/javascript">
    $(function() {
        if ('{{ request.GET.q }}' !== '') {
            $searchFieldset = $('form.search fieldset');
            $searchFieldset.append('<a href="#" class="reset">x</a>');
            $anc = $('a.reset', $searchFieldset);
            $anc.click(function() {
                $anc.siblings('input[name="q"]')
                    .val('')
                    .attr('placeholder', 'Loading...');
                $anc.hide();
                $searchFieldset.parent().submit();
                return false;
            });
        }
    });
</script>

templates/teams/_team_video_detail.html
{% load i18n teams_tags to_json %}

<li class="team_video_listing_{{ team_video.id }}">

    <div class="thumb">
        <a href="{% url "videos:video" video_id=video.video_id %}" title="{{ video.title_display }}">
            <img src="{{ video.get_thumbnail}}" alt="{{ video.title_display }} thumbnail">
        </a>
        {% with tasks=video.num_tasks language_count=video.num_completed_languages %}
            {% if tasks %}
                <a href="{% url "teams:team_tasks" slug=team.slug %}?team_video={{ team_video.id }}&lang=all&assignee=anyone" class="languages">
                    {% blocktrans count tasks as num %}
                        {{ num }} language needed
                    {% plural %}
                        {{ num }} languages needed
                    {% endblocktrans %}
                </a>
            {% else %}
                <a href="{% url "videos:video" video_id=video.video_id %}" class="languages">
                    {% blocktrans count language_count as num %}
                        {{ num }} language
                    {% plural %}
                        {{ num }} languages
                    {% endblocktrans %}
                </a>
            {% endif %}
        {% endwith %}
        <h4>
            <a href="{% url "videos:video" video_id=video.video_id %}" title="{{ video.title_display }}">{{ video.title_display|truncatewords:9 }}</a>
        </h4>
    </div>
    <ul class="admin-controls">
        {% with team_video|can_edit_video:request.user as can_edit_this_video %}
            {% if can_edit_this_video %}
                {% if team.slug|lower == 'tedx-import' or team.slug|lower == 'tedxtalks-prep' or team.slug|lower == 'tedxtalks-import' %}
                    <li>
                        <a href="{% url "videos:set_original_language" video.video_id %}" title="Set language">Set language</a>
                    </li>
                {% endif %}
                {% if team.workflow_enabled %}
                    <li>
                        <a href="{% url "teams:team_tasks" slug=team.slug %}?team_video={{ team_video.id }}" title="Manage tasks">{% trans 'Tasks' %}</a>
                    </li>
                {% endif %}

                <li>
                    <a href="{% url "teams:team_video" team_video_pk=team_video.id %}" title="Edit this video">{% trans 'Edit' %}</a>
                </li>

                <li>
                    <form action="{% url "teams:remove_video" team_video_pk=team_video.id %}" method="post" style="display: none;">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}" />
                    </form>
                    <a class="remove-video open-modal" href="#remove-modal" title="Remove this video from the team">{% trans 'Remove' %}</a>
                </li>
            {% endif %}
        {% endwith %}
    </ul>


    <script type="text/javascript">
        $('a.team_video_{{ team_video.id }}').click(function(){
            unisubs.api.openUnisubsDialogOnsite(
                '{{video.video_id}}',
                '{{video_url}}',
                GLOBAL_WIDGET_SETTINGS
            );
            return false;
        });
    </script>
</li>

templates/teams/_team_video_summary.html
{% load i18n teams_tags to_json %}

<li class="team_video_listing_{{ team_video.id }}">
  <input class="bulkable" type="checkbox" value="{{ team_video.id }}" name="selected_videos[]">
    <div class="thumb">
        <a href="{% url "videos:video" video_id=video.video_id %}" title="{{ video.title_display }}">
            <img src="{{ video.get_thumbnail }}" alt="{{ video.title_display }} thumbnail">
        </a>
        {% with tasks=video.num_tasks language_count=video.num_completed_languages %}
            {% if tasks %}
                <a href="{% url "teams:team_tasks" slug=team.slug %}?team_video={{ team_video.id }}&lang=all&assignee=anyone" class="languages">
                    {% blocktrans count tasks as num %}
                        {{ num }} language needed
                    {% plural %}
                        {{ num }} languages needed
                    {% endblocktrans %}
                </a>
            {% else %}
                <a href="{% url "videos:video" video_id=video.video_id %}" class="languages">
                    {% blocktrans count language_count as num %}
                        {{ num }} language
                    {% plural %}
                        {{ num }} languages
                    {% endblocktrans %}
                </a>
            {% endif %}
        {% endwith %}
        <h4>
            <a href="{% url "videos:video" video_id=video.video_id %}" title="{{ video.title_display }}">{{ video.title_display|truncatewords:9 }}</a>
        </h4>
    </div>
    <ul class="admin-controls">
        {% with team_video|can_edit_video:request.user as can_edit_this_video %}
            {% if can_edit_this_video %}
                {% if team.slug|lower == 'tedx-import' or team.slug|lower == 'tedxtalks-prep' or team.slug|lower == 'tedxtalks-import' %}
                    <li>
                        <a href="{% url "videos:set_original_language" video.video_id %}" title="Set language">Set language</a>
                    </li>
                {% endif %}
                {% if team.workflow_enabled %}
                    <li>
                        <a href="{% url "teams:team_tasks" slug=team.slug %}?team_video={{ team_video.id }}" title="Manage tasks">{% trans 'Tasks' %}</a>
                    </li>
                {% endif %}

                <li>
                    <a href="{% url "teams:team_video" team_video_pk=team_video.id %}" title="Edit this video">{% trans 'Edit' %}</a>
                </li>

                <li>
                    <form action="{% url "teams:remove_video" team_video_pk=team_video.id %}" method="post" style="display: none;">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}" />
                    </form>
                    <a class="remove-video open-modal" href="#remove-modal" title="Remove this video from the team">{% trans 'Remove' %}</a>
                </li>
            {% endif %}
        {% endwith %}
    </ul>


    <script type="text/javascript">
        $('a.team_video_{{ team_video.id }}').click(function(){
            unisubs.api.openUnisubsDialogOnsite(
                '{{video.video_id}}',
                '{{video_url}}',
                GLOBAL_WIDGET_SETTINGS
            );
            return false;
        });
    </script>
</li>