apps/search/urls.py
# Amara, universalsubtitles.org
# 
# Copyright (C) 2013 Participatory Culture Foundation
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see 
# http://www.gnu.org/licenses/agpl-3.0.html.

from django.conf.urls import url

from search import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^router/$', views.rpc_router, name='rpc_router'),
    url(r'^router/api/$', views.rpc_router.api, name='rpc_api'),
]

urls.py
# Amara, universalsubtitles.org
#
# Copyright (C) 2013 Participatory Culture Foundation
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see
# http://www.gnu.org/licenses/agpl-3.0.html.

import importlib

from django import http
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.models import AnonymousUser
from django.shortcuts import render
from django.template import RequestContext, loader
from django.views.generic.base import TemplateView, RedirectView
from django.views.decorators.clickjacking import xframe_options_exempt
import django.contrib.auth.views
import django.views.static

from auth.forms import CustomPasswordResetForm
from utils.genericviews import JSTemplateView
import optionalapps
import api.views
import auth.views
import crossdomain_views
import teams.views
import videos.views
import views
import widget.views

admin.autodiscover()
admin.site.login = auth.views.login

def calc_homepage_view():
    module_name, func_name = settings.HOMEPAGE_VIEW.rsplit('.', 1)
    mod = importlib.import_module(module_name)
    return getattr(mod, func_name)

urlpatterns = [
    url('^500/$', TemplateView.as_view(template_name='500.html')),
    url('^404/$', TemplateView.as_view(template_name='404.html')),
    url('^robots.txt$', TemplateView.as_view(template_name='robots.txt')),
    url(r'^crossdomain.xml$',
        crossdomain_views.root_crossdomain),
    url(r'^comments/',
        include('comments.urls', namespace='comments')),
    url(r'^messages/',
        include('messages.urls', namespace='messages')),
    # TODO: Not sure what this is.  It's breaking the app under Django 1.4
    # url(r'^pcf-targetter/',
    #     include('targetter.urls', namespace='targetter')),
    url(r'^logout/', auth.views.logout, name='logout'),
    url(r'^errortest', views.errortest, name='errortest'),
    url(r'^one_time_url/(?P<token>.+)$', views.one_time_url, name='one_time_url'),
    url(r'^admin/billing/$', teams.views.billing, name='billing'),
    url(r'^admin/password_reset/$', auth.views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$',
        django.contrib.auth.views.password_reset_done,
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        '(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth.views.password_reset_confirm, {'post_reset_redirect': '/reset/done/'}, name='password_reset_confirm'),
    url(r'^reset-external/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        django.contrib.auth.views.password_reset_confirm,
        {'extra_context': {'external_account': True}, 'post_reset_redirect': '/reset/done/'},
        name='password_reset_confirm_external'),
    url(r'^reset/done/$', auth.views.password_reset_complete,
        name='password_reset_complete'),
    url(r'^styleguide/', include('styleguide.urls', namespace='styleguide')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^staff/', include('staff.urls', namespace='staff')),
    url(r'^subtitles/',
        include('subtitles.urls', namespace='subtitles')),
    url(r'^embed(?P<version_no>\d+)?.js$', widget.views.embed,
        name="widget-embed"),
    url(r'^onsite_widget/$',
        widget.views.onsite_widget, name='onsite_widget'),
    url(r'^onsite_widget_resume/$', widget.views.onsite_widget_resume,
        name='onsite_widget_resume'),
    url(r'^widget/', include('widget.urls', namespace='widget',
        app_name='widget')),
    url(r'^search/',
        include('search.urls', 'search')),
    url(r'^community$',
        TemplateView.as_view(template_name='community.html'),
        name='community'),
    url(r'^dfxp-wrapper-test/$',
        TemplateView.as_view(template_name='dfxp-wrapper-test.html'),
        name='dfxp-wrapper-test'),
    url(r'^embedder/$', TemplateView.as_view(template_name='embedder.html'),
        'embedder_page'),
    url(r'^embedder-iframe/$',
        JSTemplateView.as_view(template_name='embedder-iframe.js'),
        name='embedder_iframe'),
    url(r'^embedder-offsite/$',
        TemplateView.as_view(template_name='embedder-offsite.html'),
        name='embedder_page_offsite'),
    url(r'^embedder-widget-iframe/(?P<analytics>.*)', widget.views.embedder_widget, name='embedder_widget'),
    url(r'^streaming-transcript/$',
        TemplateView.as_view(template_name='streaming-transcript.html'),
        name='streaming_transcript_demo'),
    url(r'^w3c/p3p.xml$',
        TemplateView.as_view(template_name='p3p.xml')),
    url(r'^w3c/Policies.xml$',
        TemplateView.as_view(template_name='Policies.xml'),
        name='policy_page'),
    url(r'^about$', TemplateView.as_view(template_name='about.html'),
        name='about_page'),
    url(r'^security', TemplateView.as_view(template_name='security.html'),
        name='security_page'),
    url(r'^get-code/$',
        TemplateView.as_view(template_name='embed_page.html'),
        name='get_code_page'),
    url(r'^dmca$',  TemplateView.as_view(template_name='dmca.html'),
        name='dmca_page'),
    url(r'^faq$',  TemplateView.as_view(template_name='faq.html'),
        name='faq_page'),
    url(r'^terms$', RedirectView.as_view(url='https://about.amara.org/tos/')),
    url(r'^opensubtitles2010$',
        TemplateView.as_view(template_name='opensubtitles2010.html'),
        name='opensubtitles2010_page'),
    url(r'^test-ogg$',
        TemplateView.as_view(template_name='alpha-test01-ogg.htm'),
        name='test-ogg-page'),
    url(r'^test-mp4$',
        TemplateView.as_view(template_name='alpha-test01-mp4.htm'),
        name='test-mp4-page'),
    url(r"helpers/",
        include('testhelpers.urls', namespace='helpers')),
    url(r'^videos/', include('videos.urls', namespace='videos',
        app_name='videos')),
    url(r'^teams/', include('teams.urls', namespace='teams',
        app_name='teams')),
    url(r'^ui/', include('ui.urls', namespace='ui', app_name='ui')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles',
        app_name='profiles')),
    url(r'^externalsites/', include('externalsites.urls',
                                    namespace='externalsites',
                                    app_name='externalsites')),
    url(r'^media/', include('staticmedia.urls',
                            namespace='staticmedia',
                            app_name='staticmedia')),
    url(r'^auth/', include('auth.urls', namespace='auth', app_name='auth')),
    url(r'^auth/', include('thirdpartyaccounts.urls', namespace='thirdpartyaccounts', app_name='thirdpartyaccounts')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^api2/partners/', include('api.urls', namespace='api-legacy')),
    ## Video shortlinks
    url(r'^v/(?P<encoded_pk>\w+)/$', videos.views.shortlink,
        name='shortlink'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^commit$', RedirectView.as_view(
        url='https://github.com/pculture/unisubs/commit/{}'.format(settings.LAST_COMMIT_GUID))),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^$', calc_homepage_view(), name="home"),
]

urlpatterns.extend(optionalapps.get_urlpatterns())

urlpatterns.extend([
    url(r'^api/', api.views.index.not_found, name='api-not-found'),
])

if settings.DEBUG:
    urlpatterns += [
        url(r'^site_media/(?P<path>.*)$', django.views.static.serve,
            {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
        url(r'^user-data/(?P<path>.*)$', django.views.static.serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    ]
try:
    import debug_toolbar
except ImportError:
    pass
else:
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

def ensure_user(request):
    if not hasattr(request, 'user'):
        request.user = AnonymousUser()

def handler500(request):
    ensure_user(request)
    return render(request, '500.html', status=500)

def handler403(request, exception):
    ensure_user(request)
    return render(request, '403.html', status=403)

apps/search/models.py
# Amara, universalsubtitles.org
# 
# Copyright (C) 2013 Participatory Culture Foundation
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see 
# http://www.gnu.org/licenses/agpl-3.0.html.

apps/search/forms.py
# Amara, universalsubtitles.org
#
# Copyright (C) 2013 Participatory Culture Foundation
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see
# http://www.gnu.org/licenses/agpl-3.0.html.

from django import forms
from django.db.models import Count
from django.utils.translation import ugettext_lazy as _

from utils.translation import get_language_choices
from videos.models import Video

_sorted_language_choices = None
def sorted_language_choices():
    # query the DB to get the language list.  Save it in a variable and keep
    # the ordering the same.  We'll assume that the language ordering doesn't
    # change between container restarts.
    global _sorted_language_choices
    if _sorted_language_choices is None:
        _sorted_language_choices = _calc_sorted_language_choices()
    return _sorted_language_choices

def _calc_sorted_language_choices():
    qs = (Video.objects.order_by()
          .values_list('primary_audio_language_code')
          .annotate(count=Count('primary_audio_language_code')))
    language_counts = dict(qs)
    choices = get_language_choices(flat=True)
    choices.sort(key=lambda c: language_counts.get(c[0], 0), reverse=True)
    return [('', _('All Languages'))] + choices

class SearchForm(forms.Form):
    SORT_CHOICES = (
        ('score', _(u'Relevance')),
        ('languages_count', _(u'Most languages')),
        ('today_views', _(u'Views Today')),
        ('week_views', _(u'Views This Week')),
        ('month_views', _(u'Views This Month')),
        ('total_views', _(u'Total Views')),
    )
    q = forms.CharField(label=_(u'query'), required=False)
    langs = forms.ChoiceField(choices=[], required=False, label=_(u'Subtitled Into'),
                              help_text=_(u'Left blank for any language'), initial='')
    video_lang = forms.ChoiceField(choices=[], required=False, label=_(u'Video In'),
                              help_text=_(u'Left blank for any language'), initial='')

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)

        self.fields['video_lang'].choices = sorted_language_choices()
        self.fields['langs'].choices = sorted_language_choices()

    def queryset(self):
        q = self.data.get('q')
        video_lang = self.data.get('video_lang')
        langs = self.data.get('langs')

        qs = Video.objects.public()
        if q:
            qs = qs.search(q)
        if video_lang:
            qs = qs.filter(primary_audio_language_code=video_lang)
        if langs:
            qs = qs.has_completed_language(langs)

        return qs

apps/search/views.py
# Amara, universalsubtitles.org
#
# Copyright (C) 2013 Participatory Culture Foundation
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see
# http://www.gnu.org/licenses/agpl-3.0.html.
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.utils.http import urlencode

from search.forms import SearchForm
from search.rpc import SearchApiClass
from utils import render_to
from utils.context_processors import current_site
from django.contrib.auth.decorators import login_required
from utils.rpc import RpcRouter


rpc_router = RpcRouter('search:rpc_router', {
    'SearchApi': SearchApiClass()
})
@login_required
@render_to('search/search.html')
def index(request):
    if request.GET:
        site = current_site(request)
        query = {}
        for k,v in request.GET.items():
            query[k] = v
        # If we're at a URL with query params we just got here from a search
        # form on another page.  If that's the case, we'll redirect to the
        # AJAX-style URL with the params in the hash.  Then that page will take
        # the other branch of this if, and the search form will work its
        # frontend magic.
        url = '%s%s#/?%s' % (
            # Safari/WebKit seem to need this to work properly when redirecting
            # over HTTPS.  See commit 92de5dd6c4969c4c4a3d5d1422fb9caf5e42f345.
            site['BASE_URL'],
            reverse('search:index'),
            urlencode(query)
        )

        return HttpResponseRedirect(url)
    else:
        return {
            'form': SearchForm(),
        }

templates/search/_search_filter.html
{% load i18n %}

<div id="sidebar"></div><!-- // sidebar -->
<script type="text/javascript">
    (function($){
        $('.more-link', $('#sidebar')).live('click', function(){
            var $ul = $(this).parents('ul');
            
            if ($ul.find('li:hidden').length){
                $ul.find('li:hidden').show();
            }else{
                var i = $ul.find('li').index($(this));
                $ul.find('li:gt('+i+')').hide();
            }

            return false;
        });
    })(jQuery);
</script>

templates/search/_search_form.html
{% load i18n %}

<form method="get" action="{% url "search:index" %}" class="search-form">
    <div id="watch_search">
        <span class="icon"></span>
        {{ form.q }}
        {% if not simple %}
            <a id="advanced_search" class="btn_active" href=""></a>
        {% endif %}
        <script type="text/javascript">
            jQuery('#id_q').input_replacement({
                text: '{% trans "Search videos" %}',
                prefocus_class: 'prefocus'
            });
            jQuery('#advanced_search').click(function(){
                jQuery('#advanced_menu').toggleClass('open');
                return false;
            });
        </script>
        {% if not simple %}
            <div id="advanced_menu">
                <div class="clearfix"></div>
                <div class="menu_item videos_in">
                    <h3>{% trans "Videos In" %}</h3>
                    {{ form.video_lang }}
                </div>
                <div class="menu_item">
                    <h3>{% trans "Subtitles into" %}</h3>
                    {{ form.langs }}
                    <button>
                        {% trans "Search" %}
                    </button>
                </div>
            </div>
        {% endif %}
    </div>
</form>

templates/search/_sidebar.html
{% load i18n utils_tags %}

<h2>{{ form.video_lang.label }}</h2>
{% form_field_as_list rdata form.video_lang 6 %}

<h2>{{ form.langs.label }}</h2>
{% form_field_as_list rdata form.langs 6 %}

templates/search/_video_item.html
{% load i18n subtitles_tags %}

<li>
  {% if not display_mode or display_mode == 'all' or display_mode == 'thumbnails' %}
  <a href="{{ video.get_absolute_url }}" class="thumbnail_medium">
      {% if video.thumbnail %}<img height="100" src="{{ video.get_thumbnail }}" />{% endif %}
  </a>
  {% endif %}
  <div class="info clearfix">
  	<h4><a href="{{ video.get_absolute_url }}">{{ video }}</a></h4>
    <p style="margin: 0 0 15px 0;">{{ video.description|striptags|truncatewords:5|linebreaksbr|urlize }}</p>  
    <div class="lang_avail">
      <h2>
          {% blocktrans count video.languages_count as number %}
              {{ number }} language
          {% plural %}
              {{ number }} languages
          {% endblocktrans %}
      </h2>
          {% for lang in video.langs_cache %}
            {% with lang.subtitle_count as lines_count %}
              {% if lines_count %}  
              <a href="{{ lang.get_absolute_url }}">
                  <!-- <span>{{ lines_count }} {% trans "lines" %}</span> -->
                  <span class="{% complete_color lang %}"></span>
                  {{ lang.language_display }}
              </a>
              {% endif %}
            {% endwith %}
          {% endfor %}
    </div><!-- // lang_avail -->
  </div><!-- // info -->
</li>

templates/search/search.html
{% extends "base.html" %}

{% load i18n search_tags media_bundle %}

{% block body_attrs %}id="watch_results"{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{% url "videos:rpc_api" %}" type="text/javascript"></script>
    <script src="{% url "search:rpc_api" %}" type="text/javascript"></script> 
    {% media_bundle 'ajax-paginator.js' %}
    <script type="text/javascript">
        jQuery(function($){
            //Add handlers for sidebar filtering links
            $('a', $('#sidebar')).live('click', function(){
                var $this = $(this);

                if ($this.attr('name') && $this.attr('value') !== undefined){
                    $this.parents('ul').find('li.active').removeClass('active');
                    $this.parents('li').addClass('active');
                    
                    $.address.parameter($this.attr('name'), $this.attr('value'));
                    $('.ajax-pagination').ajaxPaginator('refresh');
                    return false;
                }
            });
            
            //Add handler for search form submit
            var $form = $('form.search-form');
            var $q_input = $form.find('input[name=q]');
            
            var handle_form = function($form){
                var q = $q_input.val();
                if ( ! $q_input.val()){
                    return
                };
                
                $.each($form.serializeArray(), function(i, item){
                    $.address.parameter(item.name, item.value);
                });

                $('.ajax-pagination').ajaxPaginator('setPage', 1);
            };
            
            $form.submit(function(e){
                e.preventDefault();
                handle_form($(this));
                return false;
            });
            
            //This is hack for FF. Don't know why but not "preventDefault",
            //not "return false" can't prevent submit on Enter press
            $form.keypress(function(e){
                if (e.keyCode == 13){
                    handle_form($(this));
                    return false;
                }
            });
            
            var prev_query = null;

            function decodeEntities(q) {
                var textArea = document.createElement('textarea');
                textArea.innerHTML = q;
                return textArea.value;
            }
            
            //Init AJAX-paginator
            $('.ajax-pagination').ajaxPaginator({
                container: $('#main_col'),
                onPageChange: function(page, callback, parameters){
                    parameters['page'] = page;
                    parameters['q'] = decodeEntities(parameters['q']);

                    if (parameters['q']){
                        var q = parameters['q'];
                        if (q === ' '){
                            $('.search-header').text('{% trans "Search Videos" %}');
                        }else{
                            $('.search-header').text('{% trans "Search Results for" %} '+q);
                        }
                        if ($q_input.val() != q){
                            $q_input.val(q);
                        }
                    };

                    prev_query = parameters['q'];
                    
                    SearchApi.search(parameters, function(data){
                        $('.loading-indicator').remove();
                        $('.search-page').show();
                        $('#sidebar').html(data.sidebar);
                        callback.call(this, data);

                        // Override default 'no videos' text if we 
                        // think we're currently reindexing Solr
                        if(data.is_indexing){
                            $('.video_list .empty').html('Rebuilding video index. Please try again a bit later...');
                        }
                    }, this);
                },
            });
        });
    </script>
{% endblock %}

{% block main_content %}
<div class="pod" id="featured_videos">
    <div class="hd">
        {% search_form form 1 %}
        <h2 class="search-header">
            {% if result_list %}
            {% blocktrans %}
                Search Results for {{ query }}
            {% endblocktrans %}
            {% else %}
                {% trans "Search Videos" %}
            {% endif %}
        </h2>
    </div><!-- // hd -->
    <div class="bd clearfix loading-indicator">
        <div style="text-align: center; padding: 75px">
            <img class="placeholder" align="absmiddle" width="256" height1="30" src="{{ STATIC_URL }}images/ajax-loader.gif"/>
        </div>        
    </div>
    <div class="bd clearfix search-page" {% if not result_list %}style="display: none"{% endif %}>
        {% include 'search/_search_filter.html' %}
        <div id="main_col">
            <div style="text-align: center; padding: 75px">
                <img class="placeholder" align="absmiddle" width="256" height1="30" src="{{ STATIC_URL }}images/ajax-loader.gif"/>
            </div>
        </div><!-- // main_col -->
        
        <div class="clearfix"></div>
        
        <div class="pages ajax-pagination clearfix">
            <a class="pag_prev" href=""><span class="icon"></span></a>
            <span class="page_count page-info">
                <span class="from-value"></span> - 
                <span class="to-value"></span> 
                {% trans "of" %} 
                <span class="total-value"></span>
                {% trans "videos" %}           
            </span>
            <span class="page_count loading-indicator" style="display: none;">
                {% trans "Loading..." %}
            </span>            
            <a class="pag_next" href=""><span class="icon"></span></a>
        </div>      
    </div><!-- // bd -->
</div><!-- // pod -->
{% endblock %}