apps/videos/urls.py
# Amara, universalsubtitles.org
#
# Copyright (C) 2013 Participatory Culture Foundation
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see
# http://www.gnu.org/licenses/agpl-3.0.html.

from django.conf.urls import url

from videos import views

urlpatterns = [
    url(r'^watch/$', views.watch_page, name='watch_page'),
    url(r'^watch/featured/$', views.featured_videos, name='featured_videos'),
    url(r'^watch/latest/$', views.latest_videos, name='latest_videos'),
    url(r'^search/', views.search, name='search'),
    url(r'^router/$', views.rpc_router, name='rpc_router'),
    url(r'^router/api/$', views.rpc_router.api, name='rpc_api'),
    url(r'^subscribe_to_updates/$', views.subscribe_to_updates, name='subscribe_to_updates'),
    url(r'^upload_subtitles/$', views.upload_subtitles, name='upload_subtitles'),
    url(r'^create/$', views.create, name='create'),
    url(r'^activities/(?P<video_id>(\w|-)+)/$', views.activity, name='activity'),
    url(r'^stop_notification/(?P<video_id>(\w|-)+)/$', views.stop_notification, name='stop_notification'),
    url(r'^rollback/(?P<pk>\d+)/$', views.rollback, name='rollback'),
    url(r'^diffing/(?P<pk>\d+)/(?P<second_pk>\d+)/$', views.diffing, name='diffing'),
    url(r'^video_url_make_primary/$', views.video_url_make_primary, name='video_url_make_primary'),
    url(r'^video_url_create/$', views.video_url_create, name='video_url_create'),
    url(r'^video_url_remove/$', views.video_url_remove, name='video_url_remove'),
    url(r'^search-urls/$', views.url_search, name='url-search'),
    url(r'^(?P<video_id>(\w|-)+)/debug/$', views.video_debug, name='video_debug'),
    url(r'^(?P<video_id>(\w|-)+)/reset_metadata/$', views.reset_metadata, name='reset_metadata'),
    url(r'^(?P<video_id>(\w|-)+)/set-original-language/$', views.set_original_language, name='set_original_language'),
    url(r'^(?P<video_id>(\w|-)+)/$', views.redirect_to_video),
    url(r'^(?P<video_id>(\w|-)+)/create_subtitles/$', views.create_subtitles, name='create_subtitles'),
    url(r'^(?P<video_id>(\w|-)+)/info/$', views.video, name='video'),
    url(r'^(?P<video_id>(\w|-)+)/info/(?P<title>[^/]+)/$', views.video, name='video_with_title'),
    url(r'^(?P<video_id>(\w|-)+)/url/(?P<video_url>\d+)/$', views.video, name='video_url'),
    url(r'^(?P<video_id>(\w|-)+)/(?P<lang>[\w\-]+)/(?P<lang_id>[\d]+)/$',
        views.subtitles, name='translation_history'),
    url(r'^(?P<video_id>(\w|-)+)/(?P<lang>[\w\-]+)/(?P<lang_id>[\d]+)/(?P<version_id>[\d]+)/$',
        views.subtitles, name='subtitleversion_detail'),
    url(r'^(?P<video_id>(\w|-)+)/(?P<lang>[\w\-]+)/$', views.legacy_history, name='translation_history_legacy'),
    url(r'(?P<video_id>(\w|-)+)/staff/delete/$', views.video_staff_delete, name='video_staff_delete'),
]

urls.py
# Amara, universalsubtitles.org
#
# Copyright (C) 2013 Participatory Culture Foundation
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see
# http://www.gnu.org/licenses/agpl-3.0.html.

import importlib

from django import http
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.models import AnonymousUser
from django.shortcuts import render
from django.template import RequestContext, loader
from django.views.generic.base import TemplateView, RedirectView
from django.views.decorators.clickjacking import xframe_options_exempt
import django.contrib.auth.views
import django.views.static

from auth.forms import CustomPasswordResetForm
from utils.genericviews import JSTemplateView
import optionalapps
import api.views
import auth.views
import crossdomain_views
import teams.views
import videos.views
import views
import widget.views

admin.autodiscover()
admin.site.login = auth.views.login

def calc_homepage_view():
    module_name, func_name = settings.HOMEPAGE_VIEW.rsplit('.', 1)
    mod = importlib.import_module(module_name)
    return getattr(mod, func_name)

urlpatterns = [
    url('^500/$', TemplateView.as_view(template_name='500.html')),
    url('^404/$', TemplateView.as_view(template_name='404.html')),
    url('^robots.txt$', TemplateView.as_view(template_name='robots.txt')),
    url(r'^crossdomain.xml$',
        crossdomain_views.root_crossdomain),
    url(r'^comments/',
        include('comments.urls', namespace='comments')),
    url(r'^messages/',
        include('messages.urls', namespace='messages')),
    # TODO: Not sure what this is.  It's breaking the app under Django 1.4
    # url(r'^pcf-targetter/',
    #     include('targetter.urls', namespace='targetter')),
    url(r'^logout/', auth.views.logout, name='logout'),
    url(r'^errortest', views.errortest, name='errortest'),
    url(r'^one_time_url/(?P<token>.+)$', views.one_time_url, name='one_time_url'),
    url(r'^admin/billing/$', teams.views.billing, name='billing'),
    url(r'^admin/password_reset/$', auth.views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$',
        django.contrib.auth.views.password_reset_done,
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        '(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth.views.password_reset_confirm, {'post_reset_redirect': '/reset/done/'}, name='password_reset_confirm'),
    url(r'^reset-external/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        django.contrib.auth.views.password_reset_confirm,
        {'extra_context': {'external_account': True}, 'post_reset_redirect': '/reset/done/'},
        name='password_reset_confirm_external'),
    url(r'^reset/done/$', auth.views.password_reset_complete,
        name='password_reset_complete'),
    url(r'^styleguide/', include('styleguide.urls', namespace='styleguide')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^staff/', include('staff.urls', namespace='staff')),
    url(r'^subtitles/',
        include('subtitles.urls', namespace='subtitles')),
    url(r'^embed(?P<version_no>\d+)?.js$', widget.views.embed,
        name="widget-embed"),
    url(r'^onsite_widget/$',
        widget.views.onsite_widget, name='onsite_widget'),
    url(r'^onsite_widget_resume/$', widget.views.onsite_widget_resume,
        name='onsite_widget_resume'),
    url(r'^widget/', include('widget.urls', namespace='widget',
        app_name='widget')),
    url(r'^search/',
        include('search.urls', 'search')),
    url(r'^community$',
        TemplateView.as_view(template_name='community.html'),
        name='community'),
    url(r'^dfxp-wrapper-test/$',
        TemplateView.as_view(template_name='dfxp-wrapper-test.html'),
        name='dfxp-wrapper-test'),
    url(r'^embedder/$', TemplateView.as_view(template_name='embedder.html'),
        'embedder_page'),
    url(r'^embedder-iframe/$',
        JSTemplateView.as_view(template_name='embedder-iframe.js'),
        name='embedder_iframe'),
    url(r'^embedder-offsite/$',
        TemplateView.as_view(template_name='embedder-offsite.html'),
        name='embedder_page_offsite'),
    url(r'^embedder-widget-iframe/(?P<analytics>.*)', widget.views.embedder_widget, name='embedder_widget'),
    url(r'^streaming-transcript/$',
        TemplateView.as_view(template_name='streaming-transcript.html'),
        name='streaming_transcript_demo'),
    url(r'^w3c/p3p.xml$',
        TemplateView.as_view(template_name='p3p.xml')),
    url(r'^w3c/Policies.xml$',
        TemplateView.as_view(template_name='Policies.xml'),
        name='policy_page'),
    url(r'^about$', TemplateView.as_view(template_name='about.html'),
        name='about_page'),
    url(r'^security', TemplateView.as_view(template_name='security.html'),
        name='security_page'),
    url(r'^get-code/$',
        TemplateView.as_view(template_name='embed_page.html'),
        name='get_code_page'),
    url(r'^dmca$',  TemplateView.as_view(template_name='dmca.html'),
        name='dmca_page'),
    url(r'^faq$',  TemplateView.as_view(template_name='faq.html'),
        name='faq_page'),
    url(r'^terms$', RedirectView.as_view(url='https://about.amara.org/tos/')),
    url(r'^opensubtitles2010$',
        TemplateView.as_view(template_name='opensubtitles2010.html'),
        name='opensubtitles2010_page'),
    url(r'^test-ogg$',
        TemplateView.as_view(template_name='alpha-test01-ogg.htm'),
        name='test-ogg-page'),
    url(r'^test-mp4$',
        TemplateView.as_view(template_name='alpha-test01-mp4.htm'),
        name='test-mp4-page'),
    url(r"helpers/",
        include('testhelpers.urls', namespace='helpers')),
    url(r'^videos/', include('videos.urls', namespace='videos',
        app_name='videos')),
    url(r'^teams/', include('teams.urls', namespace='teams',
        app_name='teams')),
    url(r'^ui/', include('ui.urls', namespace='ui', app_name='ui')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles',
        app_name='profiles')),
    url(r'^externalsites/', include('externalsites.urls',
                                    namespace='externalsites',
                                    app_name='externalsites')),
    url(r'^media/', include('staticmedia.urls',
                            namespace='staticmedia',
                            app_name='staticmedia')),
    url(r'^auth/', include('auth.urls', namespace='auth', app_name='auth')),
    url(r'^auth/', include('thirdpartyaccounts.urls', namespace='thirdpartyaccounts', app_name='thirdpartyaccounts')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^api2/partners/', include('api.urls', namespace='api-legacy')),
    ## Video shortlinks
    url(r'^v/(?P<encoded_pk>\w+)/$', videos.views.shortlink,
        name='shortlink'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^commit$', RedirectView.as_view(
        url='https://github.com/pculture/unisubs/commit/{}'.format(settings.LAST_COMMIT_GUID))),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^$', calc_homepage_view(), name="home"),
]

urlpatterns.extend(optionalapps.get_urlpatterns())

urlpatterns.extend([
    url(r'^api/', api.views.index.not_found, name='api-not-found'),
])

if settings.DEBUG:
    urlpatterns += [
        url(r'^site_media/(?P<path>.*)$', django.views.static.serve,
            {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
        url(r'^user-data/(?P<path>.*)$', django.views.static.serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    ]
try:
    import debug_toolbar
except ImportError:
    pass
else:
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

def ensure_user(request):
    if not hasattr(request, 'user'):
        request.user = AnonymousUser()

def handler500(request):
    ensure_user(request)
    return render(request, '500.html', status=500)

def handler403(request, exception):
    ensure_user(request)
    return render(request, '403.html', status=403)

apps/videos/types/forms.py
from django.utils.translation import ugettext as _
from django import settings
from django import forms

from video.types import video_type_registrar
from utils.text import fmt

class VideoURLField(forms.URLField):
    def validate(self, video_url):
        "Check if value consists only of valid emails."
            try:
                video_type = video_type_registrar.video_type_for_url(video_url)
            except VideoTypeError, e:
                raise forms.ValidationError(e)
            if not video_type:
                contact_link = fmt(
                    _('<a href="mailto:%(email)s">Contact us</a>'),
                    email=settings.FEEDBACK_EMAIL)
                for d in video_type_registrar.domains:
                    if d in video_url:
                        raise forms.ValidationError(mark_safe(fmt(
                            _(u"Please try again with a link to a video page.  "
                              "%(contact_link)s if there's a problem."),
                            contact_link=contact_link)))

                raise forms.ValidationError(mark_safe(fmt(
                    _(u"You must link to a video on a compatible site "
                      "(like YouTube) or directly to a video file that works "
                      "with HTML5 browsers. For example: "
                      "http://mysite.com/myvideo.ogg or "
                      "http://mysite.com/myipadvideo.m4v "
                      "%(contact_link)s if there's a problem"),
                    contact_link=contact_link)))
            else:
                self._video_type = video_type
                # we need to use the cannonical url as the user provided might need
                # redirection (i.e. youtu.be/fdaf/), and django's validator will
                # choke on redirection (urllib2 for python2.6), see https://unisubs.sifterapp.com/projects/12298/issues/427646/comments
                video_url = video_type_registrar.get_canonical_url(video_url)
        # Use the parent's handling of required fields, etc.
        super(forms.URLField, self).validate(video_url)
        return video_url

templates/new-teams/_activity-list.html
{% load i18n media_bundle %}

{% if page %}
<ul class="activity listing">
  {% for record in page %}
  <li>{% if use_old_messages %}{% include "activity/old_record.html" %}
      {% else %}{% include "activity/record.html" %}{% endif %}</li>
  {% endfor %}
</ul>

{% if page.has_next %}
<div class="pagination show-more-pagination">
  <a class="show-more" href="{{ request.path }}?{{ next_page_query}}"><span class="fa fa-chevron-circle-down"></span> {% trans "Show More" %}</a>
  <img class="loading-icon" src="{% static_url %}images/ajax-loader.gif">
</div>
{% endif %}
{% else %}
<p class="empty">{% trans "Sorry, no activity yet" %}...</p>
{% endif %}

templates/new-teams/activity.html
{% extends "new-teams/base.html" %}

{% load i18n %}

{% block content %}

{% include "new-teams/_activity-tabs.html" %}
{% if tab == "videos" %}
<h2>{% blocktrans %}Video Activity for {{ team }}{% endblocktrans %}</h2>
{% elif tab == "team" %}
<h2>{% blocktrans %}Team Activity for {{ team }}{% endblocktrans %}</h2>
{% endif %}
<div class="split-view">
  <div class="filters sidebar">
    <h5>{% trans "Filter and Sort" %}</h5>
    <form method="GET" action="">
      {% include "_field.html" with field=filters_form.type %}
      {% include "_field.html" with field=filters_form.video_language %}
      {% include "_field.html" with field=filters_form.subtitle_language %}
      {% include "_field.html" with field=filters_form.sort %}

      <div class="actions">
        <button class="submit">Filter</button>
        {% if filtered %}
        <a href="{% url "teams:activity" team.slug %}{% if query %}?q={{ query }}{% endif %}" class="button cancel">Clear</a>
        {% endif %}
      </div>
    </form>
  </div>
  <div class="main" id="activity-list">
    {% include "new-teams/_activity-list.html" %}
  </div>
</div>
{% endblock %}

templates/new-teams/add_members.html
{% extends "new-teams/base.html" %}

{% load i18n %}

{% block content %}

<h2>{% trans "Add members" %}</h2>
{% if summary %}
<div class="summary">
  <h3>Members successfully processed:</h3>
  <ul>
    <li>Members added: {{ summary.added }}</li>
    <li>Unknown members: {{ summary.unknown|join:", " }}</li>
    <li>Members already part of the team: {{ summary.already|join:", " }}</li>
  </ul>
</div>
{% endif %}
<form method="post" action="" class="team-invite">
  {% csrf_token %}
  {{ form.errors.role }}
  <label for="id_role">{% trans 'Assign to role' %}</label>
  {{ form.role }}
  <p>{% trans 'Important: Only new members being added to the team will be assigned this role. The members that are already in the team will not change their roles.' %}</p>
  {% include "_field.html" with field=form.members %}

  <div class="actions">
    <button class="submit">{% trans "Add" %}</button>
  </div>
</form>

{% endblock %}

templates/new-teams/application.html
{% extends "new-base.html" %}
{% load i18n %}

{% block content %}
<h2>{% trans "Apply to" %} {{ team }}</h2>

<div class="application-form-message">
  {% if team.application_message %}
  {{ team.application_message|urlize|linebreaksbr }}
  {% else %}
  <h4>{% trans "Language skill" %}</h4>
  <p>
  {% blocktrans %}
  No formal language training is required to translate for {{ team }}. But we do ask that all translators are confident in their translation abilities.
  {% endblocktrans %}
  </p>

  <h4>Time commitment</h4>
  <p>
  {% blocktrans %}
  We request that each new applicant does at least one full set of subtitles within the first week of joining. Aside from that, it’s up to you!
  {% endblocktrans %}
  </p>
  {% endif %}
</div>

<form action="" method="POST" class="team-application">
  {% csrf_token %}
  <fieldset>
    <legend>{% trans "About You" %}</legend>
    {% include "_field.html" with field=form.about_you %}
  </fieldset>
  <fieldset>
    <legend>{% trans "Languages" %}</legend>
    <label>
      <ul class="language-selects">
        <li>1) {{ form.language1 }}</li>
        <li>2) {{ form.language2 }}</li>
        <li>3) {{ form.language3 }}</li>
        <li>4) {{ form.language4 }}</li>
        <li>5) {{ form.language5 }}</li>
        <li>6) {{ form.language6 }}</li>
      </ul>
    </label>
    <p class="help">{% trans "Select the languages you can caption or translate" %}</p>
  </fieldset>

  <div class="actions">
    <a href="{{ team.get_absolute_url }}" class="button cancel">{% trans "Cancel" %}</a>
    <button class="submit">{% trans "Submit application" %}</button>
  </div>
</form>
{% endblock %}

templates/new-teams/email_invite.html
{% extends 'videos/email_base.html' %}

{% load i18n localeurl_tags %}

{% block content %}
    <p style="font-size: 12px;">
        {% blocktrans %}
            {{ team_name }} is inviting you to join their subtitling team!
        {% endblocktrans %}
        {% if message %}
            <br/>
            <br/>
            {{ message }}
        {% endif %}
        <br/>
        <br/>
        {% trans "Please click on " %}
        <a href="{{ url_base }}{{ invite_url|rmlocale }}">{% trans "this link" %}</a>        
        {% trans " to accept the invite and create an account." %}
        <br/>
        {% trans "If the above link is not working, please try copy-pasting the link below into your browser's address bar:" %}
        <br/>
        {{ url_base }}{{ invite_url|rmlocale }}
        
    </p>
{% endblock %}

{% block dont_send %}{% endblock %}

{% block stop_notification %}{% endblock %}

templates/new-teams/email_invite_accept.html
{% extends "hands_base.html" %}

{% load i18n teams_tags media_bundle %}

{% block html_attrs %}id="login"{% endblock %}
{% block main_content %}

<script>
  document.facebook_app_public_id = "{{ app_id }}";
  document.facebook_login_confirm = "{{ facebook_login_confirm }}";
</script>

{% media_bundle "login.js" %}

<div id="login-bg" class="top-banner">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div id="create-account" class="sso">
          <form class="auth-form" action="" method="post">
              <h2>{% trans "Create an Account" %}</h2>
              <h5>
              	{% blocktrans %}
              		You are one step away from joining the subtitling team of {{ team_name }}!
              	{% endblocktrans %}
              </h5>
              {% csrf_token %}
              <ul class="create-account-form">
                {{ creation_form.as_ul }}
                <li>
                  <button type="submit" value="create account"  class="green_button big">{% trans 'Create Account' %}</button>
                </li>
              </ul>
          </form>
        </div>

      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/new-teams/invite.html
{% extends "new-teams/base.html" %}

{% load i18n %}

{% block content %}

<h2>{% trans "Invite members" %}</h2>
<form method="post" action="" class="team-invite">
  {% csrf_token %}
  {% include "_error-list.html" with errors=form.non_field_errors %}
  {% include "_field.html" with field=form.username %}
  {% include "_field.html" with field=form.email %}
  {% include "_field.html" with field=form.message %}
  {% include "_field.html" with field=form.role %}

  <div class="actions">
    <button class="submit">{% trans "Invite" %}</button>
  </div>
</form>

{% endblock %}

templates/new-teams/videos.html
{% extends "new-teams/base.html" %}

{% load i18n videos_tags %}

{% block html_attrs %}id="team-videos" {{ block.super }}{% endblock %}

{% block content %}
<h2>{% blocktrans %}Videos for {{ team }}{% endblocktrans %}</h2>
<div class="split-view">
  <div class="sidebar">
    <div class="section filters">
      <h5>{% trans "Filter and Sort" %}</h5>
      <form method="GET" action="">
        {% include "_field.html" with field=filters_form.q %}
        {% if filters_form.show_project %}
        {% include "_field.html" with field=filters_form.project %}
        {% endif %}
        {% include "_field.html" with field=filters_form.has_language %}
        {% include "_field.html" with field=filters_form.missing_language %}
        {% include "_field.html" with field=filters_form.sort %}

        <div class="actions">
          <button class="submit">Filter</button>
        </div>
      </form>
    </div>

    {% if "add_form" in forms.enabled %}
    <div class="section tools">
      <button class="open-modal" data-modal="add-form">{% trans "Add Videos" %}</button>
    </div>
    {% endif %}
    {% if "add_csv" in forms.enabled %}
    <div class="section tools">
      <button class="open-modal" data-modal="add-csv-form">{% trans "Add Videos from CSV" %}</button>
    </div>
    {% endif %}
  </div>
  <div class="main">
    {% if filters_form.is_filtered %}
    <div class="current-filter-list">
      <ul>
        {% for filter_label in filters_form.get_current_filters %}
        <li>{{ filter_label }}</li>
        {% endfor %}
        <li class="reset"><a href="{% url "teams:videos" team.slug %}">{% trans "Clear filters" %}</a></li>
      </ul>
    </div>
    {% endif %}
    {% if page %}
    {% if bulk_mode_enabled %}
    <div class="select-all-thumbs"><label><input type="checkbox"> {% trans "Select all" %}</label></div>
    {% endif %}
    <ul class="thumb-list{% if bulk_mode_enabled %} bulk-mode{% endif %}">
      {% for video in page %}
      <li>
        <div class="thumb">
          <img src="{{ video.get_wide_thumbnail }}" alt="{{ video.title_display }}">
          {% if video.duration %}<div class="badge">{{ video.duration|format_duration }}</div>{% endif %}
          {% if bulk_mode_enabled %}
          <input class="selection" type="checkbox" name="team_videos" value="{{ video.id }}">
          {% endif %}
        </div>
        <div class="extra-info">{{ video.get_primary_audio_language_code_display }}</div>
        <h6 class="one-line">
          <a href="{% url "videos:video" video_id=video.video_id %}">{{ video.title_display }}</a>
        </h6>
        {% with description=video.description|urlize|linebreaks %}
        {% if "edit" in forms.enabled %}
        <div class="three-lines">{{ description }}</div>
        <button class="open-edit-modal" data-video-id="{{ video.id }}" data-modal-url="{% url "teams:videos-form" team.slug "edit" %}">{% trans "edit" %}</button>
        {% else %}
        <div class="four-lines">{{ description }}</div>
        {% endif %}
      </li>
      {% endwith %}
      {% endfor %}
    </ul>
    {% include "_new_paginator.html" %}
    <div class="total-count">
      {% if results_are_filtered %}
      {% blocktrans with count=paginator.count %}{{ count }} matching videos{% endblocktrans %}
      {% else %}
      {% blocktrans with count=paginator.count %}{{ count }} total videos{% endblocktrans %}
      {% endif %}
    </div>
    {% else %}
    <p class="empty">{% trans "No Videos found" %}</p>
    {% endif %}
  </div>
</div>
{% endblock %}
{% block bottom %}
{% if bulk_mode_enabled %}
<div class="bottom-sheet">
  {% if "bulk-edit" in forms.enabled %}
  <button class="needs-multiple-selected" data-modal-url="{% url "teams:videos-form" team.slug "bulk-edit" %}">{% trans "Bulk Edit" %}</button>
  {% endif %}
  {% if "move" in forms.enabled %}
  <button data-modal-url="{% url "teams:videos-form" team.slug "move" %}">{% trans "Move" %}</button>
  {% endif %}
  {% if "remove" in forms.enabled %}
  <button data-modal-url="{% url "teams:videos-form" team.slug "remove" %}">{% trans "Remove" %}</button>
  {% endif %}
  {% for ext_form in forms.get_extension_forms %}
  <button data-modal-url="{% url "teams:videos-form" team.slug ext_form.name %}">{{ ext_form.label }}</button>
  {% endfor %}
  <button class="dismiss deselect-all">{% trans "deselect all" %}</button>
</div>
{% endif %}

{% if "add_form" in forms.enabled %}
<aside class="modal{% if add_form.errors %} start-open{% endif %}" id="add-form">
  <h3>{% trans "Add Videos" %}</h3>
  <button class="close"></button>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% include "_non-field-errors.html" with form=add_form %}
    <input type="hidden" name="form" value="add">
    {% include "_field.html" with field=add_form.project %}
    {% include "_field.html" with field=add_form.language %}
    {% include "_field.html" with field=add_form.thumbnail %}
    {{ add_formset.management_form }}
    <table class="formset-table">
      {% for form in add_formset %}
      {{ form }}
      {% endfor %}
    </table>
    <footer class="buttons">
      <button>{% trans "Add" %}</button>
    </footer>
  </form>
</aside>
{% endif %}
{% if "add_csv" in forms.enabled %}
<aside class="modal{% if add_csv_form.errors %} start-open{% endif %}" id="add-csv-form">
  <h3>{% trans "Add Videos from CSV" %}</h3>
  <button class="close"></button>
  <p>{% trans "Please use this " %}<a href="{{ STATIC_URL }}images/template.csv" download>{% trans "CSV Import Template" %}</a>{% trans " as the basis for your import. The Video URL field is mandatory, but all other fields can be left blank." %}</p>
  <p>{% trans "A CSV file can be created with a text editor or using the export function of a spreadsheet editor." %}</p>
  <p>{% trans "Upon completion, you will receive a summary by email." %}</p>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% include "_non-field-errors.html" with form=add_csv_form %}
    <input type="hidden" name="form" value="add-csv">
    {{ add_csv_form }}
    <footer class="buttons">
      <button>{% trans "Upload" %}</button>
    </footer>
  </form>
</aside>
{% endif %}
{% endblock %}